name: Build Arch ISO with easy-arch.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - run: mkdir -p /tmp/archlive/airootfs/root/ 
    - run: cp easy-arch.sh /tmp/archlive/airootfs/root/
    - run: pacman -Sy
    - run: pacman --noconfirm -S git archiso
    - run: cp -r /usr/share/archiso/configs/releng/* /tmp/archlive
    - run: mkarchiso -v -w /tmp/archlive/work/ -o /tmp/archlive/out /tmp/archlive
    - uses: actions/upload-artifact@v2
      with:
        name: Arch Live ISO
        path: /tmp/archlive/out/*.iso
