# This workflow will build an Arch Linux ISO file with the commit on it

name: Build Arch ISO with ArchInstall Commit

on:
  push:
    branches:
      - master
      - main # In case we adopt this convention in the future
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.editorconfig'
    - '**.gitignore'
    - '**.md'
    - 'LICENSE'
    - 'PKGBUILD'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - run: pwd
    - run: find .
    - run: cat /etc/os-release
    - run: ls -lah
    - run: cp easy-arch.sh /tmp/archlive/airootfs/root/
    - run: cat /tmp/archlive/airootfs/root/.zprofile
    - run: pacman -Sy; pacman --noconfirm -S git archiso
    - run: cp -r /usr/share/archiso/configs/releng/* /tmp/archlive
    - run: find /tmp/archlive
    - run: cd /tmp/archlive;  mkarchiso -v -w work/ -o out/ ./
    - uses: actions/upload-artifact@v2
      with:
        name: Arch Live ISO
        path: /tmp/archlive/out/*.iso
