# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Downloading the latest Arch Linux ISO.
        run: wget http://mirrors.mit.edu/archlinux/iso/latest/archlinux-2021.02.01-x86_64.iso
      - name: Installing mkisofs.
        run: sudo apt-get install mkisofs -y
      - name: Creating the ISO mountpoint.
        run: mkdir ~/archiso
      - name: Mounting the ISO.
        run: sudo mount archlinux-* ~/archiso
      - name: Extracting squashfs.
        run: sudo unsquashfs ~/archiso/arch/x86_64/airootfs.sfs
      - name: Listing squashfs content
        run: ls -la ~